### ISSUE TITLE
Creating the basic structure of the project for Scarb buildpacks

### ISSUE THREAD

**Issue by wangeguo** [amp-buildpacks/scarb#1]
Creating a Golang project based on [`libcnb`](https://github.com/buildpacks/libcnb) , [`libpak`](https://github.com/paketo-buildpacks/libpak)  or [`packit`](https://github.com/paketo-buildpacks/packit)  SDK, with a basic Buildpacks specification and Go directory structure.

Reference projects / library are available:
- Framework & Library https://github.com/amp-buildpacks/samples#framework--library
- Rustup https://github.com/paketo-community/rustup
- Cargo https://github.com/paketo-community/cargo

**Comment by zouyuxuan** [comment]
i took it
